#!/bin/sh

FILE="$1"

if [ -z "$FILE" ]; then
    FILE="$(xclip -o -s clipboard)"
fi

curdir=$(dirname "$0")
uri=$("$curdir/owncloud_transform.py" "$FILE")

echo "$uri" | xclip -selection clipboard
echo "$uri" | xclip

if [ $? = 0 ]; then
    notify-send "Copied to clipboard" "$uri"
else
    notify-send -i error "Could not copy to clipboard" "Please install xclip!"
fi
